### ISSUE TITLE
Error after pip install torchmdnet

### ISSUE THREAD

**Issue by steven60411** [torchmd/torchmd-net-legacy#3]
Hi!
When I follow the last command in README.md
"pip install torchmdnet"
It will pop two lines of error said:

ERROR: Could not find a version that satisfies the requirement torchmdnet (from versions: none)
ERROR: No matching distribution found for torchmdnet

I would like to ask if anyone encountered the same problem and how to solve it?
![error](https://user-images.githubusercontent.com/77240157/140479164-9e789a33-4b49-4cdb-b78c-128d1f58cf1c.png)

**Comment by giadefa** [comment]
If you don't mind to wait there will be a substantially new version next week

**Comment by steven60411** [comment]
> If you don't mind to wait there will be a substantially new version next week

**Comment by steven60411** [comment]
Ok! Thank you. I'll wait till then.

**Comment by steven60411** [comment]
Hi!
I've noticed that you guys have deprecated this repo and made a new one.
But when I tried to go to the link "https://github.com/torchmd/torchmd-net" in the README, it will redirect to this repo.
Don't know if it is a misplacement?

**Comment by giadefa** [comment]
Not there yet

**Comment by giadefa** [comment]
done
